name: Build OpenWrt for IPQ5332

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    

    steps:
      - name: 依赖安装
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ack antlr3 asciidoc autoconf automake autopoint binutils bison \
            build-essential bzip2 ccache clang cmake cpio curl device-tree-compiler \
            flex gawk gcc-multilib g++-multilib gettext genisoimage git gperf \
            haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev \
            libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev \
            libncurses5-dev libncursesw5-dev libpython3-dev libreadline-dev \
            libssl-dev libtool llvm lrzsz msmtp ninja-build p7zip p7zip-full \
            patch pkgconf python3 python3-pyelftools python3-setuptools \
            qemu-utils rsync scons squashfs-tools subversion swig texinfo \
            uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev python3-distutils build-essential ccache ecj fastjar file g++ gawk \
            gettext git java-propose-classpath libelf-dev libncurses5-dev \
            libncursesw5-dev libssl-dev python3 python3-distutils python3-setuptools \
            python3-dev rsync subversion swig time unzip wget xmlto zlib1g-dev \
            quilt autopoint libtool-bin gperf flex bison gettext-base asciidoc dos2unix
      - name: clone仓库
        uses: actions/checkout@v4
      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      
      - name: 恢复.config配置
        run: | 
          if [ ! -f ".config.old" ]; then
            echo "错误：.config.old 文件不存在！"
            exit 1
          fi
          cp .config.old .config
          if ! grep -q "CONFIG_TARGET_qualcommax_DEVICE_qcom_ipq5332_jdcloud_be6500=y" .config; then
            echo "错误：.config 缺少设备配置！"
            exit 1
          fi
      - name: Build OpenWrt（详细调试）
        env:
          TERM: dumb
          FORCE_UNSAFE_CONFIGURE: 1
        run: |
          # 输出关键系统信息（内存/CPU）
          echo "===== 系统资源信息 ====="
          free -h
          nproc
          echo "========================"

          # 编译工具链（分步调试）
          echo "开始编译工具链..."
          make toolchain/install -j$(nproc) V=s 
         

          # 编译固件（保留完整日志）
          echo "开始编译固件..."
          make -j$(nproc) V=s 
       
          # 验证产物
          ls -l bin/targets

      - name: 上传固件产物
        uses: actions/upload-artifact@v4  # 关键修改：从 v3 升级到 v4
        with:
          name: openwrt-ipq5332-be6500
          path: bin/targets/*/*.bin  # 路径保持不变（根据实际产物路径调整）      

      - name: 上传编译日志
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            toolchain.log
            build.log
