name: Build OpenWrt for BE6500

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build-be6500.yml'
      - 'target/linux/ipq807x/*'
      - 'package/*'
      - 'feeds.conf.default'
      - 'scripts/*'

env:
  REPO_URL: https://github.com/gsy-tt/lede.git
  REPO_BRANCH: master  # 修改为实际的分支名称
  CONFIG_FILE: .config
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_COWTRANSFER: false
  UPLOAD_WETRANSFER: false
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Initialization Environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo dpkg --add-architecture i386  # 启用32位架构支持
        sudo apt-get update
        sudo apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 python2.7 unzip zlib1g-dev lib32gcc-s1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget curl swig rsync
        sudo apt-get install -y \
            perl \
            python3 \
            python3-distutils \
            python3-setuptools \
            libxml-parser-perl \
            libncurses5-dev \
            gawk \
            gettext
        sudo apt-get -y autoremove --purge
        sudo apt-get clean

    - name: Check Repository Branches
      run: |
        echo "检查仓库分支..."
        git ls-remote --heads $REPO_URL
        echo "如果上面没有列出'$REPO_BRANCH'分支，请更新REPO_BRANCH变量"

    - name: Clone Source Code
      run: |
        rm -rf lede  # 清理所有旧目录
        git clone $REPO_URL -b $REPO_BRANCH lede  # 克隆到lede目录
        cd lede
        echo "当前目录: $(pwd)"
        ls -la  # 列出目录内容，确认结构
        echo "当前分支:"
        git branch --show-current
        # 检查源码仓库状态
        echo "源码仓库信息:"
        git log -1
        git status

    - name: Update Feeds Script
      run: |
        cd lede
        # 备份原始脚本
        cp scripts/feeds scripts/feeds.bak
        # 从官方源更新feeds脚本
        curl -fsSL https://raw.githubusercontent.com/openwrt/openwrt/master/scripts/feeds -o scripts/feeds
        chmod +x scripts/feeds

    - name: Debug Feeds Command
      run: |
        cd lede
        echo "当前目录: $(pwd)"
        echo "feeds脚本权限: $(ls -l scripts/feeds)"
        echo "Perl版本: $(perl --version | head -n 1)"
        echo "尝试执行feeds命令..."
        ./scripts/feeds --help
        ./scripts/feeds list
        ./scripts/feeds update -a || { echo "更新feeds失败"; cat ./feeds.conf; exit 1; }
        ./scripts/feeds install -a

    - name: Load Custom Configuration
      run: |
        [ -e files ] && cp -r files lede/files
        [ -e $CONFIG_FILE ] && cp $CONFIG_FILE lede/.config
        chmod +x $DIY_P1_SH $DIY_P2_SH
        cd lede
        ../$DIY_P1_SH
        make defconfig
        cat .config | grep TARGET_
        cat .config | grep BE6500

    - name: Download Package
      run: |
        cd lede
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Compile Firmware
      id: compile
      run: |
        cd lede
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 V=s
        echo "======================="
        echo "Space usage:"
        echo "======================="
        df -h
        echo "======================="
        du -h --max-depth=1 ./ | sort -hr
        # 检查是否生成了固件文件
        if [ ! -d "bin/targets" ]; then
          echo "未找到固件输出目录"
          exit 1
        fi
        # 列出所有可用的目标目录
        echo "可用的目标目录:"
        ls -l bin/targets
        # 保存固件状态
        if [ -n "$(ls -A bin/targets 2>/dev/null)" ]; then
          echo "FIRMWARE_FOUND=true" >> $GITHUB_ENV
        else
          echo "FIRMWARE_FOUND=false" >> $GITHUB_ENV
        fi

    - name: Upload Build Log
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-log
        path: lede/logs

    - name: Upload Bin Directory
      uses: actions/upload-artifact@v4
      if: env.UPLOAD_BIN_DIR == 'true' && env.FIRMWARE_FOUND == 'true' && !cancelled()
      with:
        name: OpenWrt_bin
        path: lede/bin

    - name: Organize Firmware Files
      id: organize
      if: env.UPLOAD_FIRMWARE == 'true' && env.FIRMWARE_FOUND == 'true' && !cancelled()
      run: |
        cd lede/bin/targets/*/*
        rm -rf packages
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "::set-output name=status::success"

    - name: Upload Firmware to Artifacts
      uses: actions/upload-artifact@v4
      if: steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: OpenWrt_Firmware
        path: ${{ env.FIRMWARE }}

    - name: Upload Firmware to CowTransfer
      if: env.UPLOAD_COWTRANSFER == 'true' && steps.organize.outputs.status == 'success' && !cancelled()
      run: |
        curl -sL https://git.io/cowtransfer | sh
        ./cowtransfer upload -s -p 16 ${{ env.FIRMWARE }}/*

    - name: Upload Firmware to WeTransfer
      if: env.UPLOAD_WETRANSFER == 'true' && steps.organize.outputs.status == 'success' && !cancelled()
      run: |
        sudo apt-get install -y python3 python3-pip python3-setuptools
        pip3 install wetransfer
        wetransfer -s ${{ env.FIRMWARE }}/*

    - name: Upload Firmware to Release
      uses: softprops/action-gh-release@v1
      if: env.UPLOAD_RELEASE == 'true' && github.event_name == 'release' && steps.organize.outputs.status == 'success' && !cancelled()
      with:
        files: ${{ env.FIRMWARE }}/*
        tag_name: ${{ github.ref_name }}
        body: |
          OpenWrt Firmware for BE6500
          Compiled by GitHub Actions
          Date: $(date +%Y-%m-%d)
