name: Build OpenWrt for JD Cloud BE6500

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 安装依赖
      run: |
        sudo apt update && sudo apt install -y build-essential libncurses5-dev \
        flex bison libssl-dev libelf-dev git libtool autoconf

    - name: 初始化OpenWrt源码
      run: |
        git clone https://git.openwrt.org/openwrt/openwrt.git 
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: 替换设备树文件
      run: |
        cp target/linux/ipq50xx/dts/qcom-ipq5332-be6500.dts openwrt/target/linux/ipq50xx/dts/
        echo 'dtb-$(BOARD) += qcom-ipq5332-be6500' >> openwrt/target/linux/ipq50xx/Makefile

    - name: 应用编译配置
      run: |
        cd openwrt
        cp ../.config .config
        make defconfig

    - name: 开始编译
      run: |
        cd openwrt
        make -j$(nproc) V=s

    - name: 上传固件
      uses: actions/upload-artifact@v4
      with:
        name: openwrt-be6500-firmware
        path: openwrt/bin/targets/*
